/**
 * Auto-generated by `npm run gen:api`. DO NOT EDIT.
 *
 * Run the backend (cd backend && dotnet run --project src/CodeSpace.Api) then
 * `npm run gen:api` to regenerate this file from the live Swagger document.
 *
 * This placeholder makes the project build before the backend is up.
 */
export type paths = Record<string, never>;
export type components = Record<string, never>;
export type operations = Record<string, never>;
