-- 0074_data_protection_keys.sql
--
-- The shared ASP.NET Data Protection key-ring store.
--
-- WHY: model credentials + git secrets are encrypted at rest by DataProtectionPayloadEncryptor via an
-- IDataProtectionProvider. ASP.NET's DEFAULT provider keeps its key-ring per-process (ephemeral) or in a
-- node-local file keyed by the content-root path — so a credential encrypted by one pod cannot be decrypted by
-- another replica, or by the same pod after a restart / rolling deploy. The API/worker split is multi-pod by
-- design, so that default silently breaks credential decryption. CodeSpaceDataProtection.AddCodeSpaceDataProtection
-- repoints the key-ring at THIS table (PersistKeysToDbContext) under a stable application name, so every pod shares
-- one key-ring. This table is the persistence backing.
--
-- The columns mirror the framework's DataProtectionKey entity (Id / FriendlyName / Xml), mapped explicitly in
-- CodeSpaceDbContext.OnModelCreating to these exact snake_case names. `id` is identity (the key store inserts a
-- row per generated key and lets the DB assign the id). Idempotent (IF NOT EXISTS) like every prior script.

CREATE TABLE IF NOT EXISTS data_protection_keys (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    friendly_name   text,
    xml             text
);

COMMENT ON TABLE data_protection_keys IS
    'Shared ASP.NET Data Protection key-ring (PersistKeysToDbContext). Backs DataProtectionPayloadEncryptor so every '
    'API/worker pod decrypts the same model-credential / git secrets. One row per Data Protection key (Xml = the '
    'serialized, possibly self-protected key element).';
