/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRepositoriesRouteImport } from './routes/_app.repositories'
import { Route as AppTeamsTeamSlugRouteImport } from './routes/_app.teams.$teamSlug'
import { Route as AppTeamsTeamSlugIndexRouteImport } from './routes/_app.teams.$teamSlug.index'
import { Route as AppTeamsTeamSlugWorkflowsRouteImport } from './routes/_app.teams.$teamSlug.workflows'
import { Route as AppTeamsTeamSlugSettingsRouteImport } from './routes/_app.teams.$teamSlug.settings'
import { Route as AppTeamsTeamSlugRepositoriesRouteImport } from './routes/_app.teams.$teamSlug.repositories'
import { Route as AppTeamsTeamSlugAgentsRouteImport } from './routes/_app.teams.$teamSlug.agents'
import { Route as AppTeamsTeamSlugWorkflowsIndexRouteImport } from './routes/_app.teams.$teamSlug.workflows.index'
import { Route as AppTeamsTeamSlugSettingsIndexRouteImport } from './routes/_app.teams.$teamSlug.settings.index'
import { Route as AppTeamsTeamSlugRepositoriesIndexRouteImport } from './routes/_app.teams.$teamSlug.repositories.index'
import { Route as AppTeamsTeamSlugProjectsIndexRouteImport } from './routes/_app.teams.$teamSlug.projects.index'
import { Route as AppTeamsTeamSlugAgentsIndexRouteImport } from './routes/_app.teams.$teamSlug.agents.index'
import { Route as AppTeamsTeamSlugWorkflowsWorkflowIdRouteImport } from './routes/_app.teams.$teamSlug.workflows.$workflowId'
import { Route as AppTeamsTeamSlugSettingsProvidersRouteImport } from './routes/_app.teams.$teamSlug.settings.providers'
import { Route as AppTeamsTeamSlugSettingsModelCredentialsRouteImport } from './routes/_app.teams.$teamSlug.settings.model-credentials'
import { Route as AppTeamsTeamSlugRepositoriesRepoFullPathRouteImport } from './routes/_app.teams.$teamSlug.repositories.$repoFullPath'
import { Route as AppTeamsTeamSlugProjectsProjectIdRouteImport } from './routes/_app.teams.$teamSlug.projects.$projectId'
import { Route as AppTeamsTeamSlugWorkflowsWorkflowIdIndexRouteImport } from './routes/_app.teams.$teamSlug.workflows.$workflowId.index'
import { Route as AppTeamsTeamSlugRepositoriesRepoFullPathIndexRouteImport } from './routes/_app.teams.$teamSlug.repositories.$repoFullPath.index'
import { Route as AppTeamsTeamSlugWorkflowsRunsRunIdRouteImport } from './routes/_app.teams.$teamSlug.workflows.runs.$runId'
import { Route as AppTeamsTeamSlugWorkflowsWorkflowIdRunsRouteImport } from './routes/_app.teams.$teamSlug.workflows.$workflowId.runs'
import { Route as AppTeamsTeamSlugRepositoriesRepoFullPathReleasesRouteImport } from './routes/_app.teams.$teamSlug.repositories.$repoFullPath.releases'
import { Route as AppTeamsTeamSlugRepositoriesRepoFullPathPullsRouteImport } from './routes/_app.teams.$teamSlug.repositories.$repoFullPath.pulls'
import { Route as AppTeamsTeamSlugRepositoriesRepoFullPathOverviewRouteImport } from './routes/_app.teams.$teamSlug.repositories.$repoFullPath.overview'
import { Route as AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRouteImport } from './routes/_app.teams.$teamSlug.repositories.$repoFullPath.issues'
import { Route as AppTeamsTeamSlugRepositoriesRepoFullPathCodeRouteImport } from './routes/_app.teams.$teamSlug.repositories.$repoFullPath.code'
import { Route as AppTeamsTeamSlugRepositoriesRepoFullPathPullsIndexRouteImport } from './routes/_app.teams.$teamSlug.repositories.$repoFullPath.pulls.index'
import { Route as AppTeamsTeamSlugRepositoriesRepoFullPathIssuesIndexRouteImport } from './routes/_app.teams.$teamSlug.repositories.$repoFullPath.issues.index'
import { Route as AppTeamsTeamSlugRepositoriesRepoFullPathPullsNumberRouteImport } from './routes/_app.teams.$teamSlug.repositories.$repoFullPath.pulls.$number'
import { Route as AppTeamsTeamSlugRepositoriesRepoFullPathIssuesNumberRouteImport } from './routes/_app.teams.$teamSlug.repositories.$repoFullPath.issues.$number'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesRoute = AppRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamSlugRoute = AppTeamsTeamSlugRouteImport.update({
  id: '/teams/$teamSlug',
  path: '/teams/$teamSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamSlugIndexRoute = AppTeamsTeamSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeamsTeamSlugRoute,
} as any)
const AppTeamsTeamSlugWorkflowsRoute =
  AppTeamsTeamSlugWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AppTeamsTeamSlugRoute,
  } as any)
const AppTeamsTeamSlugSettingsRoute =
  AppTeamsTeamSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppTeamsTeamSlugRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesRoute =
  AppTeamsTeamSlugRepositoriesRouteImport.update({
    id: '/repositories',
    path: '/repositories',
    getParentRoute: () => AppTeamsTeamSlugRoute,
  } as any)
const AppTeamsTeamSlugAgentsRoute = AppTeamsTeamSlugAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppTeamsTeamSlugRoute,
} as any)
const AppTeamsTeamSlugWorkflowsIndexRoute =
  AppTeamsTeamSlugWorkflowsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTeamsTeamSlugWorkflowsRoute,
  } as any)
const AppTeamsTeamSlugSettingsIndexRoute =
  AppTeamsTeamSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTeamsTeamSlugSettingsRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesIndexRoute =
  AppTeamsTeamSlugRepositoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTeamsTeamSlugRepositoriesRoute,
  } as any)
const AppTeamsTeamSlugProjectsIndexRoute =
  AppTeamsTeamSlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AppTeamsTeamSlugRoute,
  } as any)
const AppTeamsTeamSlugAgentsIndexRoute =
  AppTeamsTeamSlugAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTeamsTeamSlugAgentsRoute,
  } as any)
const AppTeamsTeamSlugWorkflowsWorkflowIdRoute =
  AppTeamsTeamSlugWorkflowsWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => AppTeamsTeamSlugWorkflowsRoute,
  } as any)
const AppTeamsTeamSlugSettingsProvidersRoute =
  AppTeamsTeamSlugSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AppTeamsTeamSlugSettingsRoute,
  } as any)
const AppTeamsTeamSlugSettingsModelCredentialsRoute =
  AppTeamsTeamSlugSettingsModelCredentialsRouteImport.update({
    id: '/model-credentials',
    path: '/model-credentials',
    getParentRoute: () => AppTeamsTeamSlugSettingsRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesRepoFullPathRoute =
  AppTeamsTeamSlugRepositoriesRepoFullPathRouteImport.update({
    id: '/$repoFullPath',
    path: '/$repoFullPath',
    getParentRoute: () => AppTeamsTeamSlugRepositoriesRoute,
  } as any)
const AppTeamsTeamSlugProjectsProjectIdRoute =
  AppTeamsTeamSlugProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppTeamsTeamSlugRoute,
  } as any)
const AppTeamsTeamSlugWorkflowsWorkflowIdIndexRoute =
  AppTeamsTeamSlugWorkflowsWorkflowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTeamsTeamSlugWorkflowsWorkflowIdRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesRepoFullPathIndexRoute =
  AppTeamsTeamSlugRepositoriesRepoFullPathIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTeamsTeamSlugRepositoriesRepoFullPathRoute,
  } as any)
const AppTeamsTeamSlugWorkflowsRunsRunIdRoute =
  AppTeamsTeamSlugWorkflowsRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => AppTeamsTeamSlugWorkflowsRoute,
  } as any)
const AppTeamsTeamSlugWorkflowsWorkflowIdRunsRoute =
  AppTeamsTeamSlugWorkflowsWorkflowIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AppTeamsTeamSlugWorkflowsWorkflowIdRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesRepoFullPathReleasesRoute =
  AppTeamsTeamSlugRepositoriesRepoFullPathReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => AppTeamsTeamSlugRepositoriesRepoFullPathRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesRepoFullPathPullsRoute =
  AppTeamsTeamSlugRepositoriesRepoFullPathPullsRouteImport.update({
    id: '/pulls',
    path: '/pulls',
    getParentRoute: () => AppTeamsTeamSlugRepositoriesRepoFullPathRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesRepoFullPathOverviewRoute =
  AppTeamsTeamSlugRepositoriesRepoFullPathOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppTeamsTeamSlugRepositoriesRepoFullPathRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRoute =
  AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AppTeamsTeamSlugRepositoriesRepoFullPathRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesRepoFullPathCodeRoute =
  AppTeamsTeamSlugRepositoriesRepoFullPathCodeRouteImport.update({
    id: '/code',
    path: '/code',
    getParentRoute: () => AppTeamsTeamSlugRepositoriesRepoFullPathRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesRepoFullPathPullsIndexRoute =
  AppTeamsTeamSlugRepositoriesRepoFullPathPullsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTeamsTeamSlugRepositoriesRepoFullPathPullsRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesRepoFullPathIssuesIndexRoute =
  AppTeamsTeamSlugRepositoriesRepoFullPathIssuesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesRepoFullPathPullsNumberRoute =
  AppTeamsTeamSlugRepositoriesRepoFullPathPullsNumberRouteImport.update({
    id: '/$number',
    path: '/$number',
    getParentRoute: () => AppTeamsTeamSlugRepositoriesRepoFullPathPullsRoute,
  } as any)
const AppTeamsTeamSlugRepositoriesRepoFullPathIssuesNumberRoute =
  AppTeamsTeamSlugRepositoriesRepoFullPathIssuesNumberRouteImport.update({
    id: '/$number',
    path: '/$number',
    getParentRoute: () => AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/signin': typeof SigninRoute
  '/repositories': typeof AppRepositoriesRoute
  '/teams/$teamSlug': typeof AppTeamsTeamSlugRouteWithChildren
  '/teams/$teamSlug/agents': typeof AppTeamsTeamSlugAgentsRouteWithChildren
  '/teams/$teamSlug/repositories': typeof AppTeamsTeamSlugRepositoriesRouteWithChildren
  '/teams/$teamSlug/settings': typeof AppTeamsTeamSlugSettingsRouteWithChildren
  '/teams/$teamSlug/workflows': typeof AppTeamsTeamSlugWorkflowsRouteWithChildren
  '/teams/$teamSlug/': typeof AppTeamsTeamSlugIndexRoute
  '/teams/$teamSlug/projects/$projectId': typeof AppTeamsTeamSlugProjectsProjectIdRoute
  '/teams/$teamSlug/repositories/$repoFullPath': typeof AppTeamsTeamSlugRepositoriesRepoFullPathRouteWithChildren
  '/teams/$teamSlug/settings/model-credentials': typeof AppTeamsTeamSlugSettingsModelCredentialsRoute
  '/teams/$teamSlug/settings/providers': typeof AppTeamsTeamSlugSettingsProvidersRoute
  '/teams/$teamSlug/workflows/$workflowId': typeof AppTeamsTeamSlugWorkflowsWorkflowIdRouteWithChildren
  '/teams/$teamSlug/agents/': typeof AppTeamsTeamSlugAgentsIndexRoute
  '/teams/$teamSlug/projects/': typeof AppTeamsTeamSlugProjectsIndexRoute
  '/teams/$teamSlug/repositories/': typeof AppTeamsTeamSlugRepositoriesIndexRoute
  '/teams/$teamSlug/settings/': typeof AppTeamsTeamSlugSettingsIndexRoute
  '/teams/$teamSlug/workflows/': typeof AppTeamsTeamSlugWorkflowsIndexRoute
  '/teams/$teamSlug/repositories/$repoFullPath/code': typeof AppTeamsTeamSlugRepositoriesRepoFullPathCodeRoute
  '/teams/$teamSlug/repositories/$repoFullPath/issues': typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRouteWithChildren
  '/teams/$teamSlug/repositories/$repoFullPath/overview': typeof AppTeamsTeamSlugRepositoriesRepoFullPathOverviewRoute
  '/teams/$teamSlug/repositories/$repoFullPath/pulls': typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsRouteWithChildren
  '/teams/$teamSlug/repositories/$repoFullPath/releases': typeof AppTeamsTeamSlugRepositoriesRepoFullPathReleasesRoute
  '/teams/$teamSlug/workflows/$workflowId/runs': typeof AppTeamsTeamSlugWorkflowsWorkflowIdRunsRoute
  '/teams/$teamSlug/workflows/runs/$runId': typeof AppTeamsTeamSlugWorkflowsRunsRunIdRoute
  '/teams/$teamSlug/repositories/$repoFullPath/': typeof AppTeamsTeamSlugRepositoriesRepoFullPathIndexRoute
  '/teams/$teamSlug/workflows/$workflowId/': typeof AppTeamsTeamSlugWorkflowsWorkflowIdIndexRoute
  '/teams/$teamSlug/repositories/$repoFullPath/issues/$number': typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesNumberRoute
  '/teams/$teamSlug/repositories/$repoFullPath/pulls/$number': typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsNumberRoute
  '/teams/$teamSlug/repositories/$repoFullPath/issues/': typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesIndexRoute
  '/teams/$teamSlug/repositories/$repoFullPath/pulls/': typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsIndexRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/signin': typeof SigninRoute
  '/repositories': typeof AppRepositoriesRoute
  '/': typeof AppIndexRoute
  '/teams/$teamSlug': typeof AppTeamsTeamSlugIndexRoute
  '/teams/$teamSlug/projects/$projectId': typeof AppTeamsTeamSlugProjectsProjectIdRoute
  '/teams/$teamSlug/settings/model-credentials': typeof AppTeamsTeamSlugSettingsModelCredentialsRoute
  '/teams/$teamSlug/settings/providers': typeof AppTeamsTeamSlugSettingsProvidersRoute
  '/teams/$teamSlug/agents': typeof AppTeamsTeamSlugAgentsIndexRoute
  '/teams/$teamSlug/projects': typeof AppTeamsTeamSlugProjectsIndexRoute
  '/teams/$teamSlug/repositories': typeof AppTeamsTeamSlugRepositoriesIndexRoute
  '/teams/$teamSlug/settings': typeof AppTeamsTeamSlugSettingsIndexRoute
  '/teams/$teamSlug/workflows': typeof AppTeamsTeamSlugWorkflowsIndexRoute
  '/teams/$teamSlug/repositories/$repoFullPath/code': typeof AppTeamsTeamSlugRepositoriesRepoFullPathCodeRoute
  '/teams/$teamSlug/repositories/$repoFullPath/overview': typeof AppTeamsTeamSlugRepositoriesRepoFullPathOverviewRoute
  '/teams/$teamSlug/repositories/$repoFullPath/releases': typeof AppTeamsTeamSlugRepositoriesRepoFullPathReleasesRoute
  '/teams/$teamSlug/workflows/$workflowId/runs': typeof AppTeamsTeamSlugWorkflowsWorkflowIdRunsRoute
  '/teams/$teamSlug/workflows/runs/$runId': typeof AppTeamsTeamSlugWorkflowsRunsRunIdRoute
  '/teams/$teamSlug/repositories/$repoFullPath': typeof AppTeamsTeamSlugRepositoriesRepoFullPathIndexRoute
  '/teams/$teamSlug/workflows/$workflowId': typeof AppTeamsTeamSlugWorkflowsWorkflowIdIndexRoute
  '/teams/$teamSlug/repositories/$repoFullPath/issues/$number': typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesNumberRoute
  '/teams/$teamSlug/repositories/$repoFullPath/pulls/$number': typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsNumberRoute
  '/teams/$teamSlug/repositories/$repoFullPath/issues': typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesIndexRoute
  '/teams/$teamSlug/repositories/$repoFullPath/pulls': typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/signin': typeof SigninRoute
  '/_app/repositories': typeof AppRepositoriesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/teams/$teamSlug': typeof AppTeamsTeamSlugRouteWithChildren
  '/_app/teams/$teamSlug/agents': typeof AppTeamsTeamSlugAgentsRouteWithChildren
  '/_app/teams/$teamSlug/repositories': typeof AppTeamsTeamSlugRepositoriesRouteWithChildren
  '/_app/teams/$teamSlug/settings': typeof AppTeamsTeamSlugSettingsRouteWithChildren
  '/_app/teams/$teamSlug/workflows': typeof AppTeamsTeamSlugWorkflowsRouteWithChildren
  '/_app/teams/$teamSlug/': typeof AppTeamsTeamSlugIndexRoute
  '/_app/teams/$teamSlug/projects/$projectId': typeof AppTeamsTeamSlugProjectsProjectIdRoute
  '/_app/teams/$teamSlug/repositories/$repoFullPath': typeof AppTeamsTeamSlugRepositoriesRepoFullPathRouteWithChildren
  '/_app/teams/$teamSlug/settings/model-credentials': typeof AppTeamsTeamSlugSettingsModelCredentialsRoute
  '/_app/teams/$teamSlug/settings/providers': typeof AppTeamsTeamSlugSettingsProvidersRoute
  '/_app/teams/$teamSlug/workflows/$workflowId': typeof AppTeamsTeamSlugWorkflowsWorkflowIdRouteWithChildren
  '/_app/teams/$teamSlug/agents/': typeof AppTeamsTeamSlugAgentsIndexRoute
  '/_app/teams/$teamSlug/projects/': typeof AppTeamsTeamSlugProjectsIndexRoute
  '/_app/teams/$teamSlug/repositories/': typeof AppTeamsTeamSlugRepositoriesIndexRoute
  '/_app/teams/$teamSlug/settings/': typeof AppTeamsTeamSlugSettingsIndexRoute
  '/_app/teams/$teamSlug/workflows/': typeof AppTeamsTeamSlugWorkflowsIndexRoute
  '/_app/teams/$teamSlug/repositories/$repoFullPath/code': typeof AppTeamsTeamSlugRepositoriesRepoFullPathCodeRoute
  '/_app/teams/$teamSlug/repositories/$repoFullPath/issues': typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRouteWithChildren
  '/_app/teams/$teamSlug/repositories/$repoFullPath/overview': typeof AppTeamsTeamSlugRepositoriesRepoFullPathOverviewRoute
  '/_app/teams/$teamSlug/repositories/$repoFullPath/pulls': typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsRouteWithChildren
  '/_app/teams/$teamSlug/repositories/$repoFullPath/releases': typeof AppTeamsTeamSlugRepositoriesRepoFullPathReleasesRoute
  '/_app/teams/$teamSlug/workflows/$workflowId/runs': typeof AppTeamsTeamSlugWorkflowsWorkflowIdRunsRoute
  '/_app/teams/$teamSlug/workflows/runs/$runId': typeof AppTeamsTeamSlugWorkflowsRunsRunIdRoute
  '/_app/teams/$teamSlug/repositories/$repoFullPath/': typeof AppTeamsTeamSlugRepositoriesRepoFullPathIndexRoute
  '/_app/teams/$teamSlug/workflows/$workflowId/': typeof AppTeamsTeamSlugWorkflowsWorkflowIdIndexRoute
  '/_app/teams/$teamSlug/repositories/$repoFullPath/issues/$number': typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesNumberRoute
  '/_app/teams/$teamSlug/repositories/$repoFullPath/pulls/$number': typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsNumberRoute
  '/_app/teams/$teamSlug/repositories/$repoFullPath/issues/': typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesIndexRoute
  '/_app/teams/$teamSlug/repositories/$repoFullPath/pulls/': typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/oauth-callback'
    | '/signin'
    | '/repositories'
    | '/teams/$teamSlug'
    | '/teams/$teamSlug/agents'
    | '/teams/$teamSlug/repositories'
    | '/teams/$teamSlug/settings'
    | '/teams/$teamSlug/workflows'
    | '/teams/$teamSlug/'
    | '/teams/$teamSlug/projects/$projectId'
    | '/teams/$teamSlug/repositories/$repoFullPath'
    | '/teams/$teamSlug/settings/model-credentials'
    | '/teams/$teamSlug/settings/providers'
    | '/teams/$teamSlug/workflows/$workflowId'
    | '/teams/$teamSlug/agents/'
    | '/teams/$teamSlug/projects/'
    | '/teams/$teamSlug/repositories/'
    | '/teams/$teamSlug/settings/'
    | '/teams/$teamSlug/workflows/'
    | '/teams/$teamSlug/repositories/$repoFullPath/code'
    | '/teams/$teamSlug/repositories/$repoFullPath/issues'
    | '/teams/$teamSlug/repositories/$repoFullPath/overview'
    | '/teams/$teamSlug/repositories/$repoFullPath/pulls'
    | '/teams/$teamSlug/repositories/$repoFullPath/releases'
    | '/teams/$teamSlug/workflows/$workflowId/runs'
    | '/teams/$teamSlug/workflows/runs/$runId'
    | '/teams/$teamSlug/repositories/$repoFullPath/'
    | '/teams/$teamSlug/workflows/$workflowId/'
    | '/teams/$teamSlug/repositories/$repoFullPath/issues/$number'
    | '/teams/$teamSlug/repositories/$repoFullPath/pulls/$number'
    | '/teams/$teamSlug/repositories/$repoFullPath/issues/'
    | '/teams/$teamSlug/repositories/$repoFullPath/pulls/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/oauth-callback'
    | '/signin'
    | '/repositories'
    | '/'
    | '/teams/$teamSlug'
    | '/teams/$teamSlug/projects/$projectId'
    | '/teams/$teamSlug/settings/model-credentials'
    | '/teams/$teamSlug/settings/providers'
    | '/teams/$teamSlug/agents'
    | '/teams/$teamSlug/projects'
    | '/teams/$teamSlug/repositories'
    | '/teams/$teamSlug/settings'
    | '/teams/$teamSlug/workflows'
    | '/teams/$teamSlug/repositories/$repoFullPath/code'
    | '/teams/$teamSlug/repositories/$repoFullPath/overview'
    | '/teams/$teamSlug/repositories/$repoFullPath/releases'
    | '/teams/$teamSlug/workflows/$workflowId/runs'
    | '/teams/$teamSlug/workflows/runs/$runId'
    | '/teams/$teamSlug/repositories/$repoFullPath'
    | '/teams/$teamSlug/workflows/$workflowId'
    | '/teams/$teamSlug/repositories/$repoFullPath/issues/$number'
    | '/teams/$teamSlug/repositories/$repoFullPath/pulls/$number'
    | '/teams/$teamSlug/repositories/$repoFullPath/issues'
    | '/teams/$teamSlug/repositories/$repoFullPath/pulls'
  id:
    | '__root__'
    | '/_app'
    | '/change-password'
    | '/oauth-callback'
    | '/signin'
    | '/_app/repositories'
    | '/_app/'
    | '/_app/teams/$teamSlug'
    | '/_app/teams/$teamSlug/agents'
    | '/_app/teams/$teamSlug/repositories'
    | '/_app/teams/$teamSlug/settings'
    | '/_app/teams/$teamSlug/workflows'
    | '/_app/teams/$teamSlug/'
    | '/_app/teams/$teamSlug/projects/$projectId'
    | '/_app/teams/$teamSlug/repositories/$repoFullPath'
    | '/_app/teams/$teamSlug/settings/model-credentials'
    | '/_app/teams/$teamSlug/settings/providers'
    | '/_app/teams/$teamSlug/workflows/$workflowId'
    | '/_app/teams/$teamSlug/agents/'
    | '/_app/teams/$teamSlug/projects/'
    | '/_app/teams/$teamSlug/repositories/'
    | '/_app/teams/$teamSlug/settings/'
    | '/_app/teams/$teamSlug/workflows/'
    | '/_app/teams/$teamSlug/repositories/$repoFullPath/code'
    | '/_app/teams/$teamSlug/repositories/$repoFullPath/issues'
    | '/_app/teams/$teamSlug/repositories/$repoFullPath/overview'
    | '/_app/teams/$teamSlug/repositories/$repoFullPath/pulls'
    | '/_app/teams/$teamSlug/repositories/$repoFullPath/releases'
    | '/_app/teams/$teamSlug/workflows/$workflowId/runs'
    | '/_app/teams/$teamSlug/workflows/runs/$runId'
    | '/_app/teams/$teamSlug/repositories/$repoFullPath/'
    | '/_app/teams/$teamSlug/workflows/$workflowId/'
    | '/_app/teams/$teamSlug/repositories/$repoFullPath/issues/$number'
    | '/_app/teams/$teamSlug/repositories/$repoFullPath/pulls/$number'
    | '/_app/teams/$teamSlug/repositories/$repoFullPath/issues/'
    | '/_app/teams/$teamSlug/repositories/$repoFullPath/pulls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories': {
      id: '/_app/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AppRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamSlug': {
      id: '/_app/teams/$teamSlug'
      path: '/teams/$teamSlug'
      fullPath: '/teams/$teamSlug'
      preLoaderRoute: typeof AppTeamsTeamSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamSlug/': {
      id: '/_app/teams/$teamSlug/'
      path: '/'
      fullPath: '/teams/$teamSlug/'
      preLoaderRoute: typeof AppTeamsTeamSlugIndexRouteImport
      parentRoute: typeof AppTeamsTeamSlugRoute
    }
    '/_app/teams/$teamSlug/workflows': {
      id: '/_app/teams/$teamSlug/workflows'
      path: '/workflows'
      fullPath: '/teams/$teamSlug/workflows'
      preLoaderRoute: typeof AppTeamsTeamSlugWorkflowsRouteImport
      parentRoute: typeof AppTeamsTeamSlugRoute
    }
    '/_app/teams/$teamSlug/settings': {
      id: '/_app/teams/$teamSlug/settings'
      path: '/settings'
      fullPath: '/teams/$teamSlug/settings'
      preLoaderRoute: typeof AppTeamsTeamSlugSettingsRouteImport
      parentRoute: typeof AppTeamsTeamSlugRoute
    }
    '/_app/teams/$teamSlug/repositories': {
      id: '/_app/teams/$teamSlug/repositories'
      path: '/repositories'
      fullPath: '/teams/$teamSlug/repositories'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesRouteImport
      parentRoute: typeof AppTeamsTeamSlugRoute
    }
    '/_app/teams/$teamSlug/agents': {
      id: '/_app/teams/$teamSlug/agents'
      path: '/agents'
      fullPath: '/teams/$teamSlug/agents'
      preLoaderRoute: typeof AppTeamsTeamSlugAgentsRouteImport
      parentRoute: typeof AppTeamsTeamSlugRoute
    }
    '/_app/teams/$teamSlug/workflows/': {
      id: '/_app/teams/$teamSlug/workflows/'
      path: '/'
      fullPath: '/teams/$teamSlug/workflows/'
      preLoaderRoute: typeof AppTeamsTeamSlugWorkflowsIndexRouteImport
      parentRoute: typeof AppTeamsTeamSlugWorkflowsRoute
    }
    '/_app/teams/$teamSlug/settings/': {
      id: '/_app/teams/$teamSlug/settings/'
      path: '/'
      fullPath: '/teams/$teamSlug/settings/'
      preLoaderRoute: typeof AppTeamsTeamSlugSettingsIndexRouteImport
      parentRoute: typeof AppTeamsTeamSlugSettingsRoute
    }
    '/_app/teams/$teamSlug/repositories/': {
      id: '/_app/teams/$teamSlug/repositories/'
      path: '/'
      fullPath: '/teams/$teamSlug/repositories/'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesIndexRouteImport
      parentRoute: typeof AppTeamsTeamSlugRepositoriesRoute
    }
    '/_app/teams/$teamSlug/projects/': {
      id: '/_app/teams/$teamSlug/projects/'
      path: '/projects'
      fullPath: '/teams/$teamSlug/projects/'
      preLoaderRoute: typeof AppTeamsTeamSlugProjectsIndexRouteImport
      parentRoute: typeof AppTeamsTeamSlugRoute
    }
    '/_app/teams/$teamSlug/agents/': {
      id: '/_app/teams/$teamSlug/agents/'
      path: '/'
      fullPath: '/teams/$teamSlug/agents/'
      preLoaderRoute: typeof AppTeamsTeamSlugAgentsIndexRouteImport
      parentRoute: typeof AppTeamsTeamSlugAgentsRoute
    }
    '/_app/teams/$teamSlug/workflows/$workflowId': {
      id: '/_app/teams/$teamSlug/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/teams/$teamSlug/workflows/$workflowId'
      preLoaderRoute: typeof AppTeamsTeamSlugWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppTeamsTeamSlugWorkflowsRoute
    }
    '/_app/teams/$teamSlug/settings/providers': {
      id: '/_app/teams/$teamSlug/settings/providers'
      path: '/providers'
      fullPath: '/teams/$teamSlug/settings/providers'
      preLoaderRoute: typeof AppTeamsTeamSlugSettingsProvidersRouteImport
      parentRoute: typeof AppTeamsTeamSlugSettingsRoute
    }
    '/_app/teams/$teamSlug/settings/model-credentials': {
      id: '/_app/teams/$teamSlug/settings/model-credentials'
      path: '/model-credentials'
      fullPath: '/teams/$teamSlug/settings/model-credentials'
      preLoaderRoute: typeof AppTeamsTeamSlugSettingsModelCredentialsRouteImport
      parentRoute: typeof AppTeamsTeamSlugSettingsRoute
    }
    '/_app/teams/$teamSlug/repositories/$repoFullPath': {
      id: '/_app/teams/$teamSlug/repositories/$repoFullPath'
      path: '/$repoFullPath'
      fullPath: '/teams/$teamSlug/repositories/$repoFullPath'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathRouteImport
      parentRoute: typeof AppTeamsTeamSlugRepositoriesRoute
    }
    '/_app/teams/$teamSlug/projects/$projectId': {
      id: '/_app/teams/$teamSlug/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/teams/$teamSlug/projects/$projectId'
      preLoaderRoute: typeof AppTeamsTeamSlugProjectsProjectIdRouteImport
      parentRoute: typeof AppTeamsTeamSlugRoute
    }
    '/_app/teams/$teamSlug/workflows/$workflowId/': {
      id: '/_app/teams/$teamSlug/workflows/$workflowId/'
      path: '/'
      fullPath: '/teams/$teamSlug/workflows/$workflowId/'
      preLoaderRoute: typeof AppTeamsTeamSlugWorkflowsWorkflowIdIndexRouteImport
      parentRoute: typeof AppTeamsTeamSlugWorkflowsWorkflowIdRoute
    }
    '/_app/teams/$teamSlug/repositories/$repoFullPath/': {
      id: '/_app/teams/$teamSlug/repositories/$repoFullPath/'
      path: '/'
      fullPath: '/teams/$teamSlug/repositories/$repoFullPath/'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathIndexRouteImport
      parentRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathRoute
    }
    '/_app/teams/$teamSlug/workflows/runs/$runId': {
      id: '/_app/teams/$teamSlug/workflows/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/teams/$teamSlug/workflows/runs/$runId'
      preLoaderRoute: typeof AppTeamsTeamSlugWorkflowsRunsRunIdRouteImport
      parentRoute: typeof AppTeamsTeamSlugWorkflowsRoute
    }
    '/_app/teams/$teamSlug/workflows/$workflowId/runs': {
      id: '/_app/teams/$teamSlug/workflows/$workflowId/runs'
      path: '/runs'
      fullPath: '/teams/$teamSlug/workflows/$workflowId/runs'
      preLoaderRoute: typeof AppTeamsTeamSlugWorkflowsWorkflowIdRunsRouteImport
      parentRoute: typeof AppTeamsTeamSlugWorkflowsWorkflowIdRoute
    }
    '/_app/teams/$teamSlug/repositories/$repoFullPath/releases': {
      id: '/_app/teams/$teamSlug/repositories/$repoFullPath/releases'
      path: '/releases'
      fullPath: '/teams/$teamSlug/repositories/$repoFullPath/releases'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathReleasesRouteImport
      parentRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathRoute
    }
    '/_app/teams/$teamSlug/repositories/$repoFullPath/pulls': {
      id: '/_app/teams/$teamSlug/repositories/$repoFullPath/pulls'
      path: '/pulls'
      fullPath: '/teams/$teamSlug/repositories/$repoFullPath/pulls'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsRouteImport
      parentRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathRoute
    }
    '/_app/teams/$teamSlug/repositories/$repoFullPath/overview': {
      id: '/_app/teams/$teamSlug/repositories/$repoFullPath/overview'
      path: '/overview'
      fullPath: '/teams/$teamSlug/repositories/$repoFullPath/overview'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathOverviewRouteImport
      parentRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathRoute
    }
    '/_app/teams/$teamSlug/repositories/$repoFullPath/issues': {
      id: '/_app/teams/$teamSlug/repositories/$repoFullPath/issues'
      path: '/issues'
      fullPath: '/teams/$teamSlug/repositories/$repoFullPath/issues'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRouteImport
      parentRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathRoute
    }
    '/_app/teams/$teamSlug/repositories/$repoFullPath/code': {
      id: '/_app/teams/$teamSlug/repositories/$repoFullPath/code'
      path: '/code'
      fullPath: '/teams/$teamSlug/repositories/$repoFullPath/code'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathCodeRouteImport
      parentRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathRoute
    }
    '/_app/teams/$teamSlug/repositories/$repoFullPath/pulls/': {
      id: '/_app/teams/$teamSlug/repositories/$repoFullPath/pulls/'
      path: '/'
      fullPath: '/teams/$teamSlug/repositories/$repoFullPath/pulls/'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsIndexRouteImport
      parentRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsRoute
    }
    '/_app/teams/$teamSlug/repositories/$repoFullPath/issues/': {
      id: '/_app/teams/$teamSlug/repositories/$repoFullPath/issues/'
      path: '/'
      fullPath: '/teams/$teamSlug/repositories/$repoFullPath/issues/'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesIndexRouteImport
      parentRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRoute
    }
    '/_app/teams/$teamSlug/repositories/$repoFullPath/pulls/$number': {
      id: '/_app/teams/$teamSlug/repositories/$repoFullPath/pulls/$number'
      path: '/$number'
      fullPath: '/teams/$teamSlug/repositories/$repoFullPath/pulls/$number'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsNumberRouteImport
      parentRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsRoute
    }
    '/_app/teams/$teamSlug/repositories/$repoFullPath/issues/$number': {
      id: '/_app/teams/$teamSlug/repositories/$repoFullPath/issues/$number'
      path: '/$number'
      fullPath: '/teams/$teamSlug/repositories/$repoFullPath/issues/$number'
      preLoaderRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesNumberRouteImport
      parentRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRoute
    }
  }
}

interface AppTeamsTeamSlugAgentsRouteChildren {
  AppTeamsTeamSlugAgentsIndexRoute: typeof AppTeamsTeamSlugAgentsIndexRoute
}

const AppTeamsTeamSlugAgentsRouteChildren: AppTeamsTeamSlugAgentsRouteChildren =
  {
    AppTeamsTeamSlugAgentsIndexRoute: AppTeamsTeamSlugAgentsIndexRoute,
  }

const AppTeamsTeamSlugAgentsRouteWithChildren =
  AppTeamsTeamSlugAgentsRoute._addFileChildren(
    AppTeamsTeamSlugAgentsRouteChildren,
  )

interface AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRouteChildren {
  AppTeamsTeamSlugRepositoriesRepoFullPathIssuesNumberRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesNumberRoute
  AppTeamsTeamSlugRepositoriesRepoFullPathIssuesIndexRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesIndexRoute
}

const AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRouteChildren: AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRouteChildren =
  {
    AppTeamsTeamSlugRepositoriesRepoFullPathIssuesNumberRoute:
      AppTeamsTeamSlugRepositoriesRepoFullPathIssuesNumberRoute,
    AppTeamsTeamSlugRepositoriesRepoFullPathIssuesIndexRoute:
      AppTeamsTeamSlugRepositoriesRepoFullPathIssuesIndexRoute,
  }

const AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRouteWithChildren =
  AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRoute._addFileChildren(
    AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRouteChildren,
  )

interface AppTeamsTeamSlugRepositoriesRepoFullPathPullsRouteChildren {
  AppTeamsTeamSlugRepositoriesRepoFullPathPullsNumberRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsNumberRoute
  AppTeamsTeamSlugRepositoriesRepoFullPathPullsIndexRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsIndexRoute
}

const AppTeamsTeamSlugRepositoriesRepoFullPathPullsRouteChildren: AppTeamsTeamSlugRepositoriesRepoFullPathPullsRouteChildren =
  {
    AppTeamsTeamSlugRepositoriesRepoFullPathPullsNumberRoute:
      AppTeamsTeamSlugRepositoriesRepoFullPathPullsNumberRoute,
    AppTeamsTeamSlugRepositoriesRepoFullPathPullsIndexRoute:
      AppTeamsTeamSlugRepositoriesRepoFullPathPullsIndexRoute,
  }

const AppTeamsTeamSlugRepositoriesRepoFullPathPullsRouteWithChildren =
  AppTeamsTeamSlugRepositoriesRepoFullPathPullsRoute._addFileChildren(
    AppTeamsTeamSlugRepositoriesRepoFullPathPullsRouteChildren,
  )

interface AppTeamsTeamSlugRepositoriesRepoFullPathRouteChildren {
  AppTeamsTeamSlugRepositoriesRepoFullPathCodeRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathCodeRoute
  AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRouteWithChildren
  AppTeamsTeamSlugRepositoriesRepoFullPathOverviewRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathOverviewRoute
  AppTeamsTeamSlugRepositoriesRepoFullPathPullsRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathPullsRouteWithChildren
  AppTeamsTeamSlugRepositoriesRepoFullPathReleasesRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathReleasesRoute
  AppTeamsTeamSlugRepositoriesRepoFullPathIndexRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathIndexRoute
}

const AppTeamsTeamSlugRepositoriesRepoFullPathRouteChildren: AppTeamsTeamSlugRepositoriesRepoFullPathRouteChildren =
  {
    AppTeamsTeamSlugRepositoriesRepoFullPathCodeRoute:
      AppTeamsTeamSlugRepositoriesRepoFullPathCodeRoute,
    AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRoute:
      AppTeamsTeamSlugRepositoriesRepoFullPathIssuesRouteWithChildren,
    AppTeamsTeamSlugRepositoriesRepoFullPathOverviewRoute:
      AppTeamsTeamSlugRepositoriesRepoFullPathOverviewRoute,
    AppTeamsTeamSlugRepositoriesRepoFullPathPullsRoute:
      AppTeamsTeamSlugRepositoriesRepoFullPathPullsRouteWithChildren,
    AppTeamsTeamSlugRepositoriesRepoFullPathReleasesRoute:
      AppTeamsTeamSlugRepositoriesRepoFullPathReleasesRoute,
    AppTeamsTeamSlugRepositoriesRepoFullPathIndexRoute:
      AppTeamsTeamSlugRepositoriesRepoFullPathIndexRoute,
  }

const AppTeamsTeamSlugRepositoriesRepoFullPathRouteWithChildren =
  AppTeamsTeamSlugRepositoriesRepoFullPathRoute._addFileChildren(
    AppTeamsTeamSlugRepositoriesRepoFullPathRouteChildren,
  )

interface AppTeamsTeamSlugRepositoriesRouteChildren {
  AppTeamsTeamSlugRepositoriesRepoFullPathRoute: typeof AppTeamsTeamSlugRepositoriesRepoFullPathRouteWithChildren
  AppTeamsTeamSlugRepositoriesIndexRoute: typeof AppTeamsTeamSlugRepositoriesIndexRoute
}

const AppTeamsTeamSlugRepositoriesRouteChildren: AppTeamsTeamSlugRepositoriesRouteChildren =
  {
    AppTeamsTeamSlugRepositoriesRepoFullPathRoute:
      AppTeamsTeamSlugRepositoriesRepoFullPathRouteWithChildren,
    AppTeamsTeamSlugRepositoriesIndexRoute:
      AppTeamsTeamSlugRepositoriesIndexRoute,
  }

const AppTeamsTeamSlugRepositoriesRouteWithChildren =
  AppTeamsTeamSlugRepositoriesRoute._addFileChildren(
    AppTeamsTeamSlugRepositoriesRouteChildren,
  )

interface AppTeamsTeamSlugSettingsRouteChildren {
  AppTeamsTeamSlugSettingsModelCredentialsRoute: typeof AppTeamsTeamSlugSettingsModelCredentialsRoute
  AppTeamsTeamSlugSettingsProvidersRoute: typeof AppTeamsTeamSlugSettingsProvidersRoute
  AppTeamsTeamSlugSettingsIndexRoute: typeof AppTeamsTeamSlugSettingsIndexRoute
}

const AppTeamsTeamSlugSettingsRouteChildren: AppTeamsTeamSlugSettingsRouteChildren =
  {
    AppTeamsTeamSlugSettingsModelCredentialsRoute:
      AppTeamsTeamSlugSettingsModelCredentialsRoute,
    AppTeamsTeamSlugSettingsProvidersRoute:
      AppTeamsTeamSlugSettingsProvidersRoute,
    AppTeamsTeamSlugSettingsIndexRoute: AppTeamsTeamSlugSettingsIndexRoute,
  }

const AppTeamsTeamSlugSettingsRouteWithChildren =
  AppTeamsTeamSlugSettingsRoute._addFileChildren(
    AppTeamsTeamSlugSettingsRouteChildren,
  )

interface AppTeamsTeamSlugWorkflowsWorkflowIdRouteChildren {
  AppTeamsTeamSlugWorkflowsWorkflowIdRunsRoute: typeof AppTeamsTeamSlugWorkflowsWorkflowIdRunsRoute
  AppTeamsTeamSlugWorkflowsWorkflowIdIndexRoute: typeof AppTeamsTeamSlugWorkflowsWorkflowIdIndexRoute
}

const AppTeamsTeamSlugWorkflowsWorkflowIdRouteChildren: AppTeamsTeamSlugWorkflowsWorkflowIdRouteChildren =
  {
    AppTeamsTeamSlugWorkflowsWorkflowIdRunsRoute:
      AppTeamsTeamSlugWorkflowsWorkflowIdRunsRoute,
    AppTeamsTeamSlugWorkflowsWorkflowIdIndexRoute:
      AppTeamsTeamSlugWorkflowsWorkflowIdIndexRoute,
  }

const AppTeamsTeamSlugWorkflowsWorkflowIdRouteWithChildren =
  AppTeamsTeamSlugWorkflowsWorkflowIdRoute._addFileChildren(
    AppTeamsTeamSlugWorkflowsWorkflowIdRouteChildren,
  )

interface AppTeamsTeamSlugWorkflowsRouteChildren {
  AppTeamsTeamSlugWorkflowsWorkflowIdRoute: typeof AppTeamsTeamSlugWorkflowsWorkflowIdRouteWithChildren
  AppTeamsTeamSlugWorkflowsIndexRoute: typeof AppTeamsTeamSlugWorkflowsIndexRoute
  AppTeamsTeamSlugWorkflowsRunsRunIdRoute: typeof AppTeamsTeamSlugWorkflowsRunsRunIdRoute
}

const AppTeamsTeamSlugWorkflowsRouteChildren: AppTeamsTeamSlugWorkflowsRouteChildren =
  {
    AppTeamsTeamSlugWorkflowsWorkflowIdRoute:
      AppTeamsTeamSlugWorkflowsWorkflowIdRouteWithChildren,
    AppTeamsTeamSlugWorkflowsIndexRoute: AppTeamsTeamSlugWorkflowsIndexRoute,
    AppTeamsTeamSlugWorkflowsRunsRunIdRoute:
      AppTeamsTeamSlugWorkflowsRunsRunIdRoute,
  }

const AppTeamsTeamSlugWorkflowsRouteWithChildren =
  AppTeamsTeamSlugWorkflowsRoute._addFileChildren(
    AppTeamsTeamSlugWorkflowsRouteChildren,
  )

interface AppTeamsTeamSlugRouteChildren {
  AppTeamsTeamSlugAgentsRoute: typeof AppTeamsTeamSlugAgentsRouteWithChildren
  AppTeamsTeamSlugRepositoriesRoute: typeof AppTeamsTeamSlugRepositoriesRouteWithChildren
  AppTeamsTeamSlugSettingsRoute: typeof AppTeamsTeamSlugSettingsRouteWithChildren
  AppTeamsTeamSlugWorkflowsRoute: typeof AppTeamsTeamSlugWorkflowsRouteWithChildren
  AppTeamsTeamSlugIndexRoute: typeof AppTeamsTeamSlugIndexRoute
  AppTeamsTeamSlugProjectsProjectIdRoute: typeof AppTeamsTeamSlugProjectsProjectIdRoute
  AppTeamsTeamSlugProjectsIndexRoute: typeof AppTeamsTeamSlugProjectsIndexRoute
}

const AppTeamsTeamSlugRouteChildren: AppTeamsTeamSlugRouteChildren = {
  AppTeamsTeamSlugAgentsRoute: AppTeamsTeamSlugAgentsRouteWithChildren,
  AppTeamsTeamSlugRepositoriesRoute:
    AppTeamsTeamSlugRepositoriesRouteWithChildren,
  AppTeamsTeamSlugSettingsRoute: AppTeamsTeamSlugSettingsRouteWithChildren,
  AppTeamsTeamSlugWorkflowsRoute: AppTeamsTeamSlugWorkflowsRouteWithChildren,
  AppTeamsTeamSlugIndexRoute: AppTeamsTeamSlugIndexRoute,
  AppTeamsTeamSlugProjectsProjectIdRoute:
    AppTeamsTeamSlugProjectsProjectIdRoute,
  AppTeamsTeamSlugProjectsIndexRoute: AppTeamsTeamSlugProjectsIndexRoute,
}

const AppTeamsTeamSlugRouteWithChildren =
  AppTeamsTeamSlugRoute._addFileChildren(AppTeamsTeamSlugRouteChildren)

interface AppRouteChildren {
  AppRepositoriesRoute: typeof AppRepositoriesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTeamsTeamSlugRoute: typeof AppTeamsTeamSlugRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppRepositoriesRoute: AppRepositoriesRoute,
  AppIndexRoute: AppIndexRoute,
  AppTeamsTeamSlugRoute: AppTeamsTeamSlugRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
